name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: self-hosted  # Use your self-hosted runner here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python for testing
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Compile C++ code
        run: |
          g++ -o counting_sort Counting_roman:sort.cpp

      - name: Run Python tests
        env:
          EXECUTABLE: ./counting_sort
        run: |
          python -m unittest discover tests
        continue-on-error: false

  prepare-env:
    runs-on: self-hosted  # Use your self-hosted runner here
    needs: check-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment for tests
        run: |
          # Add setup commands for testing (like compiling C++ code if needed)
          ./setup-test-environment.sh
          
      - name: Run tests
        run: |
          ./run-tests.sh  # Assuming you have a script to run tests
