name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Run Tests"]  # This workflow depends on the "Run Tests" workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t your-docker-image .
        
      - name: Push to DockerHub
        run: |
          docker push your-docker-image
