name: Deploy Docker

on:
  workflow_run:
    workflows: ["Test Project"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yourdockeruser/your-image-name:latest .

      - name: Push image to DockerHub
        run: docker push yourdockeruser/your-image-name:latest
