name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  check-tests:
    runs-on: self-hosted  # Use your self-hosted runner here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for test scripts
        run: |
          if [ ! -f tests/test_sorting.py ]; then
            echo "Test script not found!" >&2
            exit 1
          fi
        2> napaka.txt

      - name: Upload error log
        uses: actions/upload-artifact@v3
        with:
          name: error-log
          path: napaka.txt

  prepare-env:
    runs-on: self-hosted  # Use your self-hosted runner here
    needs: check-tests
    steps:
      - name: Download error log
        uses: actions/download-artifact@v3
        with:
          name: error-log

      - name: Check error log
        run: |
          if [ -s napaka.txt ]; then
            echo "Errors detected in the first job:"
            cat napaka.txt
            exit 1
          fi

      - name: Set up environment for tests
        run: |
          ./setup-test-environment.sh

      - name: Run tests
        run: |
          ./run-tests.sh