name: Deploy Docker to DockerHub

on:
  workflow_run:
    workflows: ["Run Dockerized Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-tag
          path: image_tag.txt

      - name: Read image tag
        id: image
        run: |
          tag=$(cat image_tag.txt)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag and push image
        run: |
          docker tag ${{ steps.image.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/cpp-project:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cpp-project:latest
