name: Run Dockerized Tests

on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: self-hosted
    name: Build & Test in Docker
    steps:
      - uses: actions/checkout@v4

      - name: Generate Docker image tag
        id: tag
        run: |
          echo "tag=test-image:$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.tag.outputs.tag }} .

      - name: Run tests inside container
        run: |
          docker run --rm ${{ steps.tag.outputs.tag }}

      - name: Save Docker tag as artifact
        run: echo "${{ steps.tag.outputs.tag }}" > image_tag.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-tag
          path: image_tag.txt
