name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Run Tests"]  # This workflow depends on the "Run Tests" workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensure tests passed
    runs-on: self-hosted  # Use your self-hosted runner here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t einarmm/SortingCpp:latest .

      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: |
          docker push einarmm/SortingCpp:latest