name: Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    name: Deploy Docker Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-tag
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read image tag
        id: image
        run: |
          tag=$(cat image_tag.txt)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Tag and push image
        run: |
          docker tag ${{ steps.image.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/uni:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/uni:latest
